<a href="https://colab.research.google.com/github/gabriel180501/inteligencia-artificial/blob/main/Apriori-questao4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Regras de associação**

**Algoritmo Apriori**

**Veja: https://www.youtube.com/watch?v=0v6PiOpsJi8**

In [2]:
!pip install apyori

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5976 sha256=78735ec3df032b526824bf2f7a63a85b5f689e3f06412f17d78406ae429d96c0
  Stored in directory: /root/.cache/pip/wheels/32/2a/54/10c595515f385f3726642b10c60bf788029e8f3a1323e3913a
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [3]:
import pandas as pd
from apyori import apriori

In [6]:
#encoding = "cp1252", encoding='utf-8', encoding='latin1'etc
#base= pd.read_csv('/content/sample_data/pasta de dente python SIM.csv', ';', encoding='cp1252', header=None)
#base= pd.read_csv('/content/sample_data/pasta de dente python SIM e NÃO.csv', ';', encoding='cp1252')
base= pd.read_csv('/content/sample_data/MercadoSim.csv', ';', encoding='cp1252',header=None)
base

<ipython-input-6-3eeea7974021>:4: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only.
  base= pd.read_csv('/content/sample_data/MercadoSim.csv', ';', encoding='cp1252',header=None)

       0     1        2    3         4      5       6
0    NaN  Cafe      NaN  Pao  Manteiga    NaN     NaN
1  Leite   NaN  Cerveja  Pao  Manteiga    NaN     NaN
2    NaN  Cafe      NaN  Pao  Manteiga    NaN     NaN
3  Leite  Cafe      NaN  Pao  Manteiga    NaN     NaN
4    NaN   NaN  Cerveja  NaN       NaN    NaN     NaN
5    NaN   NaN      NaN  NaN  Manteiga    NaN     NaN
6    NaN   NaN      NaN  Pao       NaN    NaN     NaN
7    NaN   NaN      NaN  NaN       NaN    NaN  Feijao
8    NaN   NaN      NaN  NaN       NaN  Arroz  Feijao
9    NaN   NaN      NaN  NaN       NaN  Arroz     NaN

In [7]:
base.shape

(10, 7)

**O código a seguir altera a base de dados para colocar as ausências dos produtos**

In [9]:
for column in base:
    if base[column].dtype == 'float64':
        base[column] = base[column].fillna('~' + column)
    else:
        base[column] = base[column].fillna('')

In [10]:
base

       0     1        2    3         4      5       6
0         Cafe           Pao  Manteiga
1  Leite        Cerveja  Pao  Manteiga
2         Cafe           Pao  Manteiga
3  Leite  Cafe           Pao  Manteiga
4               Cerveja
5                             Manteiga
6                        Pao
7                                              Feijao
8                                       Arroz  Feijao
9                                       Arroz

In [11]:
base.shape

(10, 7)

**Como estaremos treinando um modelo a priori, que recebe entradas em formato de lista, precisamos transformar o dataframe em uma lista de transações.**

In [12]:
transacoes = []
for i in range(len(base)):
  #print(i)
  #print(base_mercado1.values[i, 0])
  transacoes.append([str(base.values[i, j]) for j in range(base.shape[1])])

In [13]:
transacoes

[['', 'Cafe', '', 'Pao', 'Manteiga', '', ''],
 ['Leite', '', 'Cerveja', 'Pao', 'Manteiga', '', ''],
 ['', 'Cafe', '', 'Pao', 'Manteiga', '', ''],
 ['Leite', 'Cafe', '', 'Pao', 'Manteiga', '', ''],
 ['', '', 'Cerveja', '', '', '', ''],
 ['', '', '', '', 'Manteiga', '', ''],
 ['', '', '', 'Pao', '', '', ''],
 ['', '', '', '', '', '', 'Feijao'],
 ['', '', '', '', '', 'Arroz', 'Feijao'],
 ['', '', '', '', '', 'Arroz', '']]

In [14]:
type(transacoes)
print(transacoes[1])

['Leite', '', 'Cerveja', 'Pao', 'Manteiga', '', '']

**Vamos chamar executar o algoritmo apriori e armazenar as regras obtidas**

In [15]:
regras = apriori(transacoes, min_support = 0.3, min_confidence = 0.8)
saida = list(regras) 
print(len(saida))
print(saida)

12
[RelationRecord(items=frozenset({''}), support=1.0, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({''}), confidence=1.0, lift=1.0)]), RelationRecord(items=frozenset({'', 'Cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({''}), confidence=1.0, lift=1.0)]), RelationRecord(items=frozenset({'', 'Manteiga'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Manteiga'}), items_add=frozenset({''}), confidence=1.0, lift=1.0)]), RelationRecord(items=frozenset({'', 'Pao'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Pao'}), items_add=frozenset({''}), confidence=1.0, lift=1.0)]), RelationRecord(items=frozenset({'Manteiga', 'Cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'Manteiga'}), confidence=1.0, lift=2.0)]), RelationRecord(items=frozenset({'Pao', 'Cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'Pao'}), confidence=1.0, lift=2.0)]), RelationRecord(items=frozenset({'Manteiga', 'Pao'}), support=0.4, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Manteiga'}), items_add=frozenset({'Pao'}), confidence=0.8, lift=1.6), OrderedStatistic(items_base=frozenset({'Pao'}), items_add=frozenset({'Manteiga'}), confidence=0.8, lift=1.6)]), RelationRecord(items=frozenset({'', 'Manteiga', 'Cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'', 'Manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'', 'Cafe'}), items_add=frozenset({'Manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'Manteiga', 'Cafe'}), items_add=frozenset({''}), confidence=1.0, lift=1.0)]), RelationRecord(items=frozenset({'', 'Pao', 'Cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'', 'Pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'', 'Cafe'}), items_add=frozenset({'Pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'Pao', 'Cafe'}), items_add=frozenset({''}), confidence=1.0, lift=1.0)]), RelationRecord(items=frozenset({'', 'Manteiga', 'Pao'}), support=0.4, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Manteiga'}), items_add=frozenset({'', 'Pao'}), confidence=0.8, lift=1.6), OrderedStatistic(items_base=frozenset({'Pao'}), items_add=frozenset({'', 'Manteiga'}), confidence=0.8, lift=1.6), OrderedStatistic(items_base=frozenset({'', 'Manteiga'}), items_add=frozenset({'Pao'}), confidence=0.8, lift=1.6), OrderedStatistic(items_base=frozenset({'', 'Pao'}), items_add=frozenset({'Manteiga'}), confidence=0.8, lift=1.6), OrderedStatistic(items_base=frozenset({'Manteiga', 'Pao'}), items_add=frozenset({''}), confidence=1.0, lift=1.0)]), RelationRecord(items=frozenset({'Manteiga', 'Cafe', 'Pao'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'Manteiga', 'Pao'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'Manteiga', 'Cafe'}), items_add=frozenset({'Pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'Pao', 'Cafe'}), items_add=frozenset({'Manteiga'}), confidence=1.0, lift=2.0)]), RelationRecord(items=frozenset({'', 'Manteiga', 'Cafe', 'Pao'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'', 'Manteiga', 'Pao'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'', 'Cafe'}), items_add=frozenset({'Manteiga', 'Pao'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'Manteiga', 'Cafe'}), items_add=frozenset({'', 'Pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'Pao', 'Cafe'}), items_add=frozenset({'', 'Manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'', 'Manteiga', 'Cafe'}), items_add=frozenset({'Pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'', 'Pao', 'Cafe'}), items_add=frozenset({'Manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'Manteiga', 'Cafe', 'Pao'}), items_add=frozenset({''}), confidence=1.0, lift=1.0)])]

In [16]:
itemsets = apriori(transacoes, min_support=0.1)#coloquei o suporte como 0.1, pois nao pode ser 0 

print(f"Itemsets utilizados no Apriori:")
for itemset in itemsets:
    print(f"{list(itemset.items)} - suporte: {itemset.support:.2f}")

Itemsets utilizados no Apriori:
[''] - suporte: 1.00
['Arroz'] - suporte: 0.20
['Cafe'] - suporte: 0.30
['Cerveja'] - suporte: 0.20
['Feijao'] - suporte: 0.20
['Leite'] - suporte: 0.20
['Manteiga'] - suporte: 0.50
['Pao'] - suporte: 0.50
['', 'Arroz'] - suporte: 0.20
['', 'Cafe'] - suporte: 0.30
['', 'Cerveja'] - suporte: 0.20
['', 'Feijao'] - suporte: 0.20
['', 'Leite'] - suporte: 0.20
['', 'Manteiga'] - suporte: 0.50
['', 'Pao'] - suporte: 0.50
['Feijao', 'Arroz'] - suporte: 0.10
['Cafe', 'Leite'] - suporte: 0.10
['Manteiga', 'Cafe'] - suporte: 0.30
['Pao', 'Cafe'] - suporte: 0.30
['Cerveja', 'Leite'] - suporte: 0.10
['Manteiga', 'Cerveja'] - suporte: 0.10
['Pao', 'Cerveja'] - suporte: 0.10
['Manteiga', 'Leite'] - suporte: 0.20
['Pao', 'Leite'] - suporte: 0.20
['Manteiga', 'Pao'] - suporte: 0.40
['', 'Feijao', 'Arroz'] - suporte: 0.10
['', 'Cafe', 'Leite'] - suporte: 0.10
['', 'Manteiga', 'Cafe'] - suporte: 0.30
['', 'Pao', 'Cafe'] - suporte: 0.30
['', 'Cerveja', 'Leite'] - suporte: 0.10
['', 'Manteiga', 'Cerveja'] - suporte: 0.10
['', 'Pao', 'Cerveja'] - suporte: 0.10
['', 'Manteiga', 'Leite'] - suporte: 0.20
['', 'Pao', 'Leite'] - suporte: 0.20
['', 'Manteiga', 'Pao'] - suporte: 0.40
['Manteiga', 'Cafe', 'Leite'] - suporte: 0.10
['Pao', 'Cafe', 'Leite'] - suporte: 0.10
['Manteiga', 'Cafe', 'Pao'] - suporte: 0.30
['Manteiga', 'Cerveja', 'Leite'] - suporte: 0.10
['Pao', 'Cerveja', 'Leite'] - suporte: 0.10
['Manteiga', 'Cerveja', 'Pao'] - suporte: 0.10
['Manteiga', 'Pao', 'Leite'] - suporte: 0.20
['', 'Manteiga', 'Cafe', 'Leite'] - suporte: 0.10
['', 'Pao', 'Cafe', 'Leite'] - suporte: 0.10
['', 'Manteiga', 'Cafe', 'Pao'] - suporte: 0.30
['', 'Manteiga', 'Cerveja', 'Leite'] - suporte: 0.10
['', 'Pao', 'Cerveja', 'Leite'] - suporte: 0.10
['', 'Manteiga', 'Cerveja', 'Pao'] - suporte: 0.10
['', 'Manteiga', 'Pao', 'Leite'] - suporte: 0.20
['Manteiga', 'Cafe', 'Pao', 'Leite'] - suporte: 0.10
['Manteiga', 'Cerveja', 'Pao', 'Leite'] - suporte: 0.10
['', 'Manteiga', 'Pao', 'Leite', 'Cafe'] - suporte: 0.10
['', 'Manteiga', 'Pao', 'Leite', 'Cerveja'] - suporte: 0.10

In [23]:
print(saida[0])

RelationRecord(items=frozenset({'nan'}), support=1.0, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan'}), confidence=1.0, lift=1.0)])

In [16]:
print(saida[1])

RelationRecord(items=frozenset({'Manteiga', 'Cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'Manteiga'}), confidence=1.0, lift=2.0)])

In [17]:
print(saida[2])

RelationRecord(items=frozenset({'Pao', 'Cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Cafe'}), items_add=frozenset({'Pao'}), confidence=1.0, lift=2.0)])

**Para facilitar a visualização, veja como transformar isso em um dataframe** 

Extraído de:

https://www.section.io/engineering-education/apriori-algorithm-in-python/

https://splunktool.com/understanding-apyoris-output

In [17]:
Antecedente = []
Consequente = []
suporte = []
confianca = []
lift = []

for resultado in saida:
  s = resultado[1]
  print(resultado[1])
  result_rules = resultado[2]
  for result_rule in result_rules:
    a = list(result_rule[0])
    b = list(result_rule[1])
    c = result_rule[2]
    l = result_rule[3]
    if 'nan' in a or 'nan' in b: continue
    if len(a) == 0 or len(b) == 0: continue
    Antecedente.append(a)
    Consequente.append(b)
    suporte.append(s)
    confianca.append(c)
    lift.append(l)
    RegrasFinais = pd.DataFrame({'Antecedente': Antecedente, 'Consequente': Consequente, 'suporte': suporte, 'confianca': confianca, 'lift': lift})

1.0
0.3
0.5
0.5
0.3
0.3
0.4
0.3
0.3
0.4
0.3
0.3

In [18]:
RegrasFinais

              Antecedente        Consequente  suporte  confianca  lift
0                  [Cafe]                 []      0.3        1.0   1.0
1              [Manteiga]                 []      0.5        1.0   1.0
2                   [Pao]                 []      0.5        1.0   1.0
3                  [Cafe]         [Manteiga]      0.3        1.0   2.0
4                  [Cafe]              [Pao]      0.3        1.0   2.0
5              [Manteiga]              [Pao]      0.4        0.8   1.6
6                   [Pao]         [Manteiga]      0.4        0.8   1.6
7                  [Cafe]       [, Manteiga]      0.3        1.0   2.0
8                [, Cafe]         [Manteiga]      0.3        1.0   2.0
9        [Manteiga, Cafe]                 []      0.3        1.0   1.0
10                 [Cafe]            [, Pao]      0.3        1.0   2.0
11               [, Cafe]              [Pao]      0.3        1.0   2.0
12            [Pao, Cafe]                 []      0.3        1.0   1.0
13             [Manteiga]            [, Pao]      0.4        0.8   1.6
14                  [Pao]       [, Manteiga]      0.4        0.8   1.6
15           [, Manteiga]              [Pao]      0.4        0.8   1.6
16                [, Pao]         [Manteiga]      0.4        0.8   1.6
17        [Manteiga, Pao]                 []      0.4        1.0   1.0
18                 [Cafe]    [Manteiga, Pao]      0.3        1.0   2.5
19       [Manteiga, Cafe]              [Pao]      0.3        1.0   2.0
20            [Pao, Cafe]         [Manteiga]      0.3        1.0   2.0
21                 [Cafe]  [, Manteiga, Pao]      0.3        1.0   2.5
22               [, Cafe]    [Manteiga, Pao]      0.3        1.0   2.5
23       [Manteiga, Cafe]            [, Pao]      0.3        1.0   2.0
24            [Pao, Cafe]       [, Manteiga]      0.3        1.0   2.0
25     [, Manteiga, Cafe]              [Pao]      0.3        1.0   2.0
26          [, Pao, Cafe]         [Manteiga]      0.3        1.0   2.0
27  [Manteiga, Cafe, Pao]                 []      0.3        1.0   1.0

**Podemos ordenar estas regras por uma métrica desejada**

In [19]:
RegrasFinais.sort_values(by='lift', ascending =False)

              Antecedente        Consequente  suporte  confianca  lift
18                 [Cafe]    [Manteiga, Pao]      0.3        1.0   2.5
22               [, Cafe]    [Manteiga, Pao]      0.3        1.0   2.5
21                 [Cafe]  [, Manteiga, Pao]      0.3        1.0   2.5
10                 [Cafe]            [, Pao]      0.3        1.0   2.0
25     [, Manteiga, Cafe]              [Pao]      0.3        1.0   2.0
19       [Manteiga, Cafe]              [Pao]      0.3        1.0   2.0
23       [Manteiga, Cafe]            [, Pao]      0.3        1.0   2.0
24            [Pao, Cafe]       [, Manteiga]      0.3        1.0   2.0
11               [, Cafe]              [Pao]      0.3        1.0   2.0
20            [Pao, Cafe]         [Manteiga]      0.3        1.0   2.0
8                [, Cafe]         [Manteiga]      0.3        1.0   2.0
7                  [Cafe]       [, Manteiga]      0.3        1.0   2.0
4                  [Cafe]              [Pao]      0.3        1.0   2.0
3                  [Cafe]         [Manteiga]      0.3        1.0   2.0
26          [, Pao, Cafe]         [Manteiga]      0.3        1.0   2.0
6                   [Pao]         [Manteiga]      0.4        0.8   1.6
13             [Manteiga]            [, Pao]      0.4        0.8   1.6
5              [Manteiga]              [Pao]      0.4        0.8   1.6
15           [, Manteiga]              [Pao]      0.4        0.8   1.6
16                [, Pao]         [Manteiga]      0.4        0.8   1.6
14                  [Pao]       [, Manteiga]      0.4        0.8   1.6
0                  [Cafe]                 []      0.3        1.0   1.0
17        [Manteiga, Pao]                 []      0.4        1.0   1.0
1              [Manteiga]                 []      0.5        1.0   1.0
12            [Pao, Cafe]                 []      0.3        1.0   1.0
9        [Manteiga, Cafe]                 []      0.3        1.0   1.0
2                   [Pao]                 []      0.5        1.0   1.0
27  [Manteiga, Cafe, Pao]                 []      0.3        1.0   1.0